### ISSUE TITLE
List of various consistent bugs i've found.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [xzxADIxzx/Join-and-kill-em-together#5] opened 2023-07-24 00:11 UTC
Overall, this mod is amazing even if it's rough in a few places: but the fact a multiplayer mod is already out, mostly functional, and really fun before any of the others is awesome.

**Deaths/Restart from checkpoint causes desync**
If a player dies, and restarts from checkpoint or is alive and restarts from checkpoint: be it the host or client player: enemy spawns and doors become desynced, as well as some bosses. Enemies will play their spawn animation, but the enemies don't exist ever. So rooms that require X amount of enemies to die, just never open or move to their next wave.

**Networked bosses for clients act as their sandbox counterparts and not the REAL boss**
Boss cutscenes don't seem to be synced, if you are a client and either you or the host kills the boss: the boss cutscene only plays for the host where as the client just sees the sandbox death animation instead. Also flesh prison transition to minos just doesn't exist.

**Flesh prison is missing his healing bar underneath his main bar if you are a client**
Simple enough, can't tell if he can't heal or not as a client though the several times I fought him he never did.

**Damaging a player on your own team still causes them to bleed, even though you deal no damage**
Not super important to fix, but could be cheesy to have each other heal endlessly between or mid-combat.

**Cybergrind pattern/wave doesn't sync**
Cybergrind doesn't seem supported at all, clients never get the wave to update nor have the terrain sync either.

**Player weapon skins use your own skin, not theirs**
Every player in the game with their weapon out will always have the skins you selected for yourself, not their own.

**Freezeframe rocket launcher doesn't sync the frozen status**
Clients just see a normal rocket be fired and explode, never frozen in the air.

**Glass panes aren't synced between checkpoints**
Self explanatory, when dying and reloading a checkpoint all glass panes you can shatter are back to normal when a client.

**Clash mode causes the player to stand completely still on other clients**
Yeah I didn't really expect clash mode to be networked but still would be cool. Also if the clash player kills another player, it breaks them completely and only their projectiles are synced, restarting from checkpoint doesn't fix it.

**5-S fishing rod is not synced visually**
Yeah that's about it lol

**Torches/skulls don't seem to be networked**
When doing P-1, we could both grab our own torch but we couldn't see the other ones torch. Don't know if this applies elsewhere, just thought to mention.

**Comment by xzxADIxzx** [comment] 2023-07-24 13:45
Thank you very much for the bugs you found, I will do this for the next eternity :D
Cheers

**Comment by xzxADIxzx** [comment] 2023-08-07 19:20
> Deaths/Restart from checkpoint causes desync
> Player weapon skins use your own skin, not theirs

This bugs are fixed :3

**Comment by Mr-Foxtrot** [comment] 2023-08-08 18:18
Awesome

**Comment by Tr1NgleDev** [comment] 2023-08-12 19:34
only the normal doors. and sometimes they bug out and we get stuck. the doors that open with skulls or the walls that move up when you kill everyone in arena dont sync at all

**Comment by xzxADIxzx** [comment] 2023-11-19 18:19
Skulls and other items r synced now

**Comment by xzxADIxzx** [comment] 2023-12-17 18:08
The Cyber Grind and rocket's freeze will be synced in 1.1.0

**Comment by xzxADIxzx** [comment] 2024-03-14 21:37
I hope I will be able to close this issue some day

**Comment by Meganium97** [comment] 2024-06-08 18:20
![20240608131839_1](https://github.com/xzxADIxzx/Join-and-kill-em-together/assets/73264332/64d29345-57cd-4961-93e6-a1fdae9174f2)
Bosses duplicate upon host death for a joined lobby

**Comment by Ardub92** [comment] 2024-06-08 18:44
> Bosses duplicate upon host death for a joined lobby

@Meganium97, please create a new issue

**Comment by Meganium97** [comment] 2024-06-09 00:24
Sorry, just thought I'd add it here since it's a consistent thing. It follows the behavior of sandbox bosses.

**Comment by Meganium97** [comment] 2024-06-09 00:27
I'd also like to add: the doors issue now no longer seems to be solely tied to host/client deaths anymore and they seem to be simply completely bugged.

**Comment by xzxADIxzx** [comment] 2024-06-09 11:24
Fixed bugs:
* Deaths/Restart from checkpoint causes desync
* Networked bosses for clients act as their sandbox counterparts and not the REAL boss
* Cybergrind pattern/wave doesn't sync
* Player weapon skins use your own skin, not theirs
* Freezeframe rocket launcher doesn't sync the frozen status
* Glass panes aren't synced between checkpoints
* Torches/skulls don't seem to be networked

Not a bug, but a lore feature:
* Damaging a player on your own team still causes them to bleed, even though you deal no damage

So I think I can close this issue (after damn year)

**Closed by xzxADIxzx** 2024-06-09 11:24 UTC
